In [48]:
import os
import cv2
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix


In [23]:
dataset_path = r"C:\Users\HP\Desktop\Programming\Projects\Prasunet Intern Projects\Project 3- SVM Dogs Cats Classification\dataset\dogs-vs-cats\train\subset"

In [24]:
# Loading Train Data

In [25]:
images = []
labels = []

In [26]:
for img_name in os.listdir(dataset_path):
    img_path = os.path.join(dataset_path, img_name)
    img = cv2.imread(img_path)
    img = cv2.resize(img, (64,64))
    images.append(img)
    if img_name.startswith("cat"):
        labels.append(0)
    elif img_name.startswith("dog"):
        labels.append(1) 



In [27]:
import numpy as np


In [28]:
images = np.array(images)
labels = np.array(labels)

In [29]:
images.shape

(2000, 64, 64, 3)

In [30]:
images = images.reshape(images.shape[0], -1)

In [31]:
images.shape

(2000, 12288)

In [32]:
from sklearn.model_selection import train_test_split

In [33]:
x_train, x_test, y_train, y_test = train_test_split(images, labels, test_size=0.2, random_state=42, stratify=labels)

In [34]:
print(x_train.shape, x_test.shape)

(1600, 12288) (400, 12288)


In [35]:
from sklearn.preprocessing import StandardScaler

In [36]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)


In [37]:
from sklearn.svm import SVC

In [23]:
svm = SVC(kernel='linear', random_state=42)
svm.fit(x_train, y_train)

SVC(kernel='linear', random_state=42)

In [26]:
y_pred = svm.predict(x_test)

In [43]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.7075

In [ ]:
#0.7075 accuracy

In [44]:
report = classification_report(y_test, y_pred)
print(report)


              precision    recall  f1-score   support

           0       0.70      0.72      0.71       200
           1       0.72      0.69      0.70       200

    accuracy                           0.71       400
   macro avg       0.71      0.71      0.71       400
weighted avg       0.71      0.71      0.71       400



In [49]:
cm = confusion_matrix(y_test, y_pred)
print(cm)


[[145  55]
 [ 62 138]]


In [45]:
svm_rbf = SVC(kernel='rbf', gamma='scale', C=1.0, random_state=42)

In [46]:
svm_rbf.fit(x_train, y_train)

SVC(random_state=42)

In [51]:
y_pred_rbf = svm_rbf.predict(x_test)

In [52]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred_rbf)

0.625

In [53]:
# 0.625 accuracy

In [55]:
report = classification_report(y_test, y_pred_rbf)
print(report)



              precision    recall  f1-score   support

           0       0.63      0.59      0.61       200
           1       0.62      0.66      0.64       200

    accuracy                           0.62       400
   macro avg       0.63      0.62      0.62       400
weighted avg       0.63      0.62      0.62       400



In [56]:
cm = confusion_matrix(y_test, y_pred_rbf)
print(cm)


[[119  81]
 [ 69 131]]


In [23]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    'C': [0.1, 1, 10, 100],
    'gamma': [1, 0.1, 0.01, 0.001],
    'kernel': ['rbf']
}

grid = GridSearchCV(SVC(), param_grid, refit=True, verbose=2, cv=5)

grid.fit(x_train, y_train)

print("Best Parameters:", grid.best_params_)
print("Best Estimator:", grid.best_estimator_)

Fitting 5 folds for each of 16 candidates, totalling 80 fits
[CV] END .........................C=0.1, gamma=1, kernel=rbf; total time= 1.5min
[CV] END .........................C=0.1, gamma=1, kernel=rbf; total time= 1.5min
[CV] END .........................C=0.1, gamma=1, kernel=rbf; total time= 1.6min
[CV] END .........................C=0.1, gamma=1, kernel=rbf; total time= 1.4min
[CV] END .........................C=0.1, gamma=1, kernel=rbf; total time=  52.3s
[CV] END .......................C=0.1, gamma=0.1, kernel=rbf; total time=  52.6s
[CV] END .......................C=0.1, gamma=0.1, kernel=rbf; total time=  53.5s
[CV] END .......................C=0.1, gamma=0.1, kernel=rbf; total time=  57.6s
[CV] END .......................C=0.1, gamma=0.1, kernel=rbf; total time= 1.2min
[CV] END .......................C=0.1, gamma=0.1, kernel=rbf; total time=  59.4s
[CV] END ......................C=0.1, gamma=0.01, kernel=rbf; total time=  58.8s
[CV] END ......................C=0.1, gamma=0.01

In [24]:
grid_predictions = grid.predict(x_test)

print(f'Validation Accuracy with Tuned RBF Kernel: {accuracy_score(y_test, grid_predictions):.2f}')

Validation Accuracy with Tuned RBF Kernel: 0.53


In [62]:
report = classification_report(y_test, grid_predictions)
print(report)


              precision    recall  f1-score   support

           0       0.52      0.87      0.65       200
           1       0.59      0.18      0.28       200

    accuracy                           0.53       400
   macro avg       0.55      0.53      0.46       400
weighted avg       0.55      0.53      0.46       400



In [63]:
cm = confusion_matrix(y_test, grid_predictions)
print(cm)


[[174  26]
 [163  37]]


In [64]:
svm_poly = SVC(kernel='poly', degree=2, random_state=42)

In [65]:
svm_poly.fit(x_train, y_train)

SVC(degree=2, kernel='poly', random_state=42)

In [66]:
y_pred_poly = svm_poly.predict(x_test)

In [67]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred_poly)

0.6375

In [68]:
# 0.6375 accuracy

In [69]:
report = classification_report(y_test, y_pred_poly)
print(report)


              precision    recall  f1-score   support

           0       0.71      0.46      0.56       200
           1       0.60      0.81      0.69       200

    accuracy                           0.64       400
   macro avg       0.66      0.64      0.63       400
weighted avg       0.66      0.64      0.63       400



In [70]:
cm = confusion_matrix(y_test, y_pred_poly)
print(cm)


[[ 92 108]
 [ 37 163]]


In [71]:
svm_poly_3 = SVC(kernel='poly', degree=3, random_state=42)

In [72]:
svm_poly_3.fit(x_train, y_train)

SVC(kernel='poly', random_state=42)

In [73]:
y_pred_3 = svm_poly_3.predict(x_test)

In [74]:
accuracy_score(y_test, y_pred_3)

0.56

In [75]:
# 0.56 accuracy

In [76]:
report = classification_report(y_test, y_pred_3)
print(report)


              precision    recall  f1-score   support

           0       0.64      0.28      0.38       200
           1       0.54      0.84      0.66       200

    accuracy                           0.56       400
   macro avg       0.59      0.56      0.52       400
weighted avg       0.59      0.56      0.52       400



In [77]:
cm = confusion_matrix(y_test, y_pred_3)
print(cm)


[[ 55 145]
 [ 31 169]]
